name: Deploy web

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: 'npm'
          cache-dependency-path: web/package-lock.json

      - name: Install wasm-pack
        uses: jetli/wasm-pack-action@v0.4.0

      - name: Cache WASM build
        uses: actions/cache@v3
        with:
          key: doesnt-matter-share-everything
          path: |
            backend/target
            graph/target

      - name: Build web app
        run: |
          cd web
          npm ci
          npm run wasm-release
          npm run build --if-present

      - name: Build docs
        run: |
          cd graph
          cargo doc --no-deps
          mv target/doc ../web/dist/

      - name: Publish
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./web/dist/
